### PR TITLE
Fix issue #25: Series in cohort hierarchy

### PR DESCRIPTION
**Pull request by dboun**
- Series in now part of cohort hierarchy
- "seg" as per the DICOM standard is a modality dedicated to segmentations. Instead of "series_description", it contains "segment_label".

Example output:
```json
{
    "cohort_name": "Cohort_Alex_Test",
    "subjects": [
        {
            "name": "Brats18_CBICA_ABM_1",
            "studies": [
                {
                    "name": "study1",
                    "series": [
                        {
                            "images": [
                                {
                                    "image_info": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABM_1/study1/mri/flair/Brats18_CBICA_ABM_1_flair.json",
                                    "path": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABM_1/study1/mri/flair/Brats18_CBICA_ABM_1_flair.nii.gz"
                                }
                            ],
                            "modality": "mri",
                            "series_description": "flair"
                        },
                        {
                            "images": [
                                {
                                    "path": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABM_1/study1/mri/t1/Brats18_CBICA_ABM_1_t1.nii.gz"
                                }
                            ],
                            "modality": "mri",
                            "series_description": "t1"
                        },
                        {
                            "images": [
                                {
                                    "path": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABM_1/study1/seg/glioblastoma/Brats18_CBICA_ABM_1_seg.nii.gz"
                                }
                            ],
                            "modality": "seg",
                            "segment_label": "glioblastoma"
                        }
                    ]
                }
            ]
        },
        {
            "name": "Brats18_CBICA_ABN_1",
            "studies": [
                {
                    "name": "study1",
                    "series": [
                        {
                            "images": [
                                {
                                    "path": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABN_1/study1/mri/t1ce/Brats18_CBICA_ABN_1_t1ce.nii.gz"
                                }
                            ],
                            "modality": "mri",
                            "series_description": "t1ce"
                        },
                        {
                            "images": [
                                {
                                    "path": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABN_1/study1/mri/t2/Brats18_CBICA_ABN_1_t2.nii.gz"
                                }
                            ],
                            "modality": "mri",
                            "series_description": "t2"
                        },
                        {
                            "images": [
                                {
                                    "image_info": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABN_1/study1/seg/qwertuy/Brats18_CBICA_ABN_1_seg.json",
                                    "path": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABN_1/study1/seg/qwertuy/Brats18_CBICA_ABN_1_seg.nii.gz"
                                }
                            ],
                            "modality": "seg",
                            "segment_label": "qwertuy"
                        }
                    ]
                },
                {
                    "name": "study2",
                    "series": [
                        {
                            "images": [
                                {
                                    "path": "/home/dimitris/Desktop/Cohort_Alex_Test/Brats18_CBICA_ABN_1/study2/seg/abc/seg.nii.gz"
                                }
                            ],
                            "modality": "seg",
                            "segment_label": "abc"
                        }
                    ]
                }
            ]
        }
    ]
}

```

### CODE REVIEW

**Review by ashishsingh18 — COMMENTED** [review]
Are these tested before merging with master?

**Comment by dboun** [comment]
> Are these tested before merging with master?

yep

**Review by ashishsingh18 — APPROVED** [review]
looks fine.

**Comment by ashishsingh18** [comment]
Please add comments..

**Comment by dboun** [comment]
> Please add comments..

Merging this now. Opened issue #32 to remember to add comments. They would be part of the next PR will all the cohort stuff

**Pull request merged**
