### PR TITLE
Rename plugins to upenn.cbica.captk.* and change view names

### LINKED ISSUE #81: All views should be changed to upenn.cbica.captk.views.*

### PR DESCRIPTION
**Pull request by dboun**
Renaming of plugins and fix #81

### CODE REVIEW

**Review by ashishsingh18 — COMMENTED** [review]
-why are the resources files here? 
-Didn't you want to put the plugin by organ name: upenn.cbica.captk.brain.x?

**Comment by dboun** [comment]
> -why are the resources files here?

Shouldn't they be? Can you be more specific as to which resources you are referring to?

> -Didn't you want to put the plugin by organ name: upenn.cbica.captk.brain.x?

Yep, but I forgot :P I will update the PR, don't merge it yet

**Comment by dboun** [comment]
(last commit: Renaming upenn.cbica.captk.phiestimator to upenn.cbica.captk.brain.phiestimator)

**Comment by dboun** [comment]
Also changed the view names

**Comment by ashishsingh18** [comment]
> 
> 
> > -why are the resources files here?
> 
> Shouldn't they be? Can you be more specific as to which resources you are referring to?

png, css, etc. Is that because the folder name got changed? 
> 
> > -Didn't you want to put the plugin by organ name: upenn.cbica.captk.brain.x?
> 
> Yep, but I forgot :P I will update the PR, don't merge it yet

**Comment by dboun** [comment]
> > > -why are the resources files here?
> > 
> > 
> > Shouldn't they be? Can you be more specific as to which resources you are referring to?
> 
> png, css, etc. Is that because the folder name got changed?

Yes, I didn't change their name. Their path just changed. (Also the qrc's changed i.e. ```<qresource prefix="/upenn.cbica.captk.ui">```

Please approve this PR if everything else is ok, because all the rest depend on this

**Review by ashishsingh18 — APPROVED** [review]

**Pull request merged**
